# Generated by Django 4.1 on 2022-12-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=30, unique=True)),
                ('created_at', models.DateTimeField(editable=False)),
                ('last_modified', models.DateTimeField()),
                ('api_key', models.CharField(max_length=100)),
            ],
        ),
    ]
