# Generated by Django 4.1 on 2022-12-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cart_alter_category_slug_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price_expires_at',
        ),
        migrations.AlterField(
            model_name='cart',
            name='last_modified',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='checked_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='last_modified',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='api_key',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
