# Generated by Django 4.1 on 2022-12-11 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_cartitem_price_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='last_modified',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='last_modified',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_modified',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_modified',
            field=models.DateTimeField(editable=False),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
