# Generated by Django 4.1 on 2022-12-12 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_order_product_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default=112, on_delete=django.db.models.deletion.CASCADE, to='api.order'),
            preserve_default=False,
        ),
    ]
