# Generated by Django 4.1 on 2022-12-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
