# Generated by Django 4.1 on 2022-12-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
