# Generated by Django 4.1 on 2022-12-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_category_deactivated_at_category_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuscode',
            name='slug',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
