# Generated by Django 4.1 on 2022-12-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_statuscode_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuscode',
            name='code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='statuscode',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
