# Generated by Django 4.1 on 2022-12-19 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_productvariant_productvariantoption_sku_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantMapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('last_modified', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(editable=False)),
                ('last_modified', models.DateTimeField(editable=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='VariantOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(editable=False)),
                ('last_modified', models.DateTimeField(editable=False)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.variant')),
            ],
        ),
        migrations.RemoveField(
            model_name='productvariantoptionmapper',
            name='product_variant_option',
        ),
        migrations.RemoveField(
            model_name='productvariantoptionmapper',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='sku',
            name='product',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='price',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='ProductVariantOption',
        ),
        migrations.DeleteModel(
            name='ProductVariantOptionMapper',
        ),
        migrations.DeleteModel(
            name='Sku',
        ),
        migrations.AddField(
            model_name='productvariantmapper',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productvariant'),
        ),
        migrations.AddField(
            model_name='productvariantmapper',
            name='variant_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.variantoption'),
        ),
    ]
