# Generated by Django 4.1 on 2022-12-20 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_productvariantmapper_variant_variantoption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('barcode', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField(editable=False)),
                ('last_modified', models.DateTimeField(editable=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='SkuMapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('last_modified', models.DateTimeField(editable=False)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sku')),
                ('variant_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.variantoption')),
            ],
        ),
        migrations.RemoveField(
            model_name='productvariantmapper',
            name='product_variant',
        ),
        migrations.RemoveField(
            model_name='productvariantmapper',
            name='variant_option',
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
        migrations.DeleteModel(
            name='ProductVariantMapper',
        ),
    ]
